feat(WEB-60): communicate API stability
rivet-gg/site pull request #111
Opened 2024-02-07 14:13 UTC by jog1t

Closes WEB-60
![image](https://github.com/rivet-gg/site/assets/39823706/945eb78d-c2f6-4d68-b4cb-c7023b9d378a)

2024-02-12 17:53 UTC, AngelOnFira requested changes

2024-02-12 17:53 UTC, AngelOnFira commented on src/pages/docs/kv/api/delete-batch.mdx
> +<Warning>This is an experimental feature - stability of the API is not guaranteed. Proceed with caution.</Warning>
Can we instead add this as a templated message in the `src/components/mdx.jsx` file? That way it's just a bit easier to change if needed :)

2024-02-17 01:32 UTC, NathanFlurry requested changes

2024-02-17 01:32 UTC, NathanFlurry commented on src/pages/docs/kv/api/delete-batch.mdx
> +<ExperimentalFeature />
This is auto-generated on `scripts/api/` iirc, should not be edited manually

2024-02-22 22:10 UTC, NathanFlurry approved these changes

2024-03-06 15:41 UTC, merged