Update tanks tutorial
rivet-gg/site pull request #129
Opened 2024-02-14 20:27 UTC by MasterPtato

Fixes WEB-128

2024-02-15 20:10 UTC, AngelOnFira approved these changes

2024-02-15 20:10 UTC, AngelOnFira commented on src/pages/learn/godot/tutorials/bomber-demo/index.mdx
Ty for the fixes on this file, good to see some items I didn't consider 🙌

2024-02-17 01:03 UTC, NathanFlurry requested changes
we should be using npm in our tutorials because a lot of people (esp newer to js) are not familiar with yarn. or the super hip js devs don't like yarn anymore. i don't remember if the example is using yarn or npm.

2024-02-17 01:03 UTC, NathanFlurry commented on src/pages/learn/html5/tutorials/crash-course.mdx
>  ### Install the Rivet library
<!--__GRAPHITE_HTML_TAG_START__--><i class='graphite__hidden'>[Re: line 55]<br/><br/></i>

<!--__GRAPHITE_HTML_TAG_END__-->Remove version<!--__GRAPHITE_HTML_TAG_START__--><span class='graphite__hidden'><br/><br/>See this comment inline on <a href="https://app.graphite.dev/github/pr/rivet-gg/site/129?utm_source=unchanged-line-comment">Graphite</a>.</span>

<!--__GRAPHITE_HTML_TAG_END__-->

2024-02-19 17:13 UTC, MasterPtato commented on src/pages/learn/html5/tutorials/tanks-canvas-socketio.mdx
> +rivet init --html5
yes, its already in the repo

2024-02-21 18:29 UTC, MasterPtato commented on src/components/mdx.jsx
> +        environment by Rivet.
Could you explain how it automatically gets added by the CDN?

2024-02-21 18:37 UTC, MasterPtato commented on src/pages/learn/html5/tutorials/tanks-canvas-socketio.mdx
> +  - Creats a version on Rivet - Deploys the version to the *Production* namespace
We don't have any docs on namespaces

2024-02-22 08:06 UTC, NathanFlurry requested changes

2024-02-22 08:06 UTC, NathanFlurry commented on src/components/mdx.jsx
> +        environment by Rivet.
https://b5a845b5.site-ckd.pages.dev/docs/general/concepts/cli-tips#build-command-environment-variables

we can restack on top of this or add a dedicated docs page later (as a ticket)

2024-02-24 00:34 UTC, MasterPtato commented on src/components/mdx.jsx
> +        environment by Rivet.
I don't see how that explains how the CDN is adding the env vars. Do you mean the CLI?

2024-02-26 19:21 UTC, NathanFlurry approved these changes

2024-02-27 21:02 UTC, merged