Document bridge vs host networking
rivet-gg/site pull request #133
Opened 2024-02-15 04:54 UTC by NathanFlurry

2024-02-15 04:55 UTC, NathanFlurry commented
Current dependencies on/for this PR:
* `main`
  * **PR #133** <a href="https://app.graphite.dev/github/pr/rivet-gg/site/133?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/site/133?utm_source=stack-comment).

2024-02-15 17:16 UTC, MasterPtato requested changes
@NathanFlurry Forgot to update the _navigation.json to include the new doc

2024-02-20 14:54 UTC, AngelOnFira approved these changes

2024-02-20 17:41 UTC, AngelOnFira approved these changes

2024-02-21 19:27 UTC, MasterPtato approved these changes

2024-02-21 23:48 UTC, MasterPtato approved these changes

2024-02-22 22:18 UTC, merged