Update API docs
rivet-gg/site pull request #134
Opened 2024-02-15 05:02 UTC by NathanFlurry

2024-02-15 05:03 UTC, NathanFlurry commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/rivet-gg/site/134?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #133** <a href="https://app.graphite.dev/github/pr/rivet-gg/site/133?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #134** <a href="https://app.graphite.dev/github/pr/rivet-gg/site/134?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/site/134?utm_source=stack-comment).

2024-02-15 17:18 UTC, MasterPtato approved these changes

2024-02-21 23:45 UTC, MasterPtato requested changes

2024-02-21 23:45 UTC, MasterPtato commented on src/pages/docs/cloud/api/devices/links/complete.mdx
> +```bash {{ title: 'cURL' }}
I think this was overwritten on accident, this needs to be valid JSON

2024-02-22 00:43 UTC, MasterPtato approved these changes

2024-02-22 22:18 UTC, merged