Update generation scripts to match latest api schema
rivet-gg/site pull request #33
Opened 2023-12-28 04:46 UTC by ABCxFF

WEB-40

2023-12-28 04:46 UTC, ABCxFF commented
Current dependencies on/for this PR:
* `main`
  * **PR #33** <a href="https://app.graphite.dev/github/pr/rivet-gg/site/33?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈
    * **PR #34** <a href="https://app.graphite.dev/github/pr/rivet-gg/site/34?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
      * **PR #35** <a href="https://app.graphite.dev/github/pr/rivet-gg/site/35?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/site/33?utm_source=stack-comment).

2023-12-28 22:29 UTC, NathanFlurry requested changes

2023-12-28 22:29 UTC, NathanFlurry commented on scripts/generateNavigation.mjs
> +      } else if (inputGroup.template?.api && apiPages[inputGroup.template.api]) {
Why is this needed?

2023-12-29 17:39 UTC, NathanFlurry commented on scripts/generateNavigation.mjs
> +      } else if (inputGroup.template?.api && apiPages[inputGroup.template.api]) {
Nevermind, it's our deprecated APIs.

2023-12-29 17:39 UTC, NathanFlurry approved these changes

2023-12-29 17:43 UTC, merged