Add redirect for discord for an easy access
rivet-gg/site pull request #37
Opened 2023-12-28 17:14 UTC by jog1t

2023-12-28 22:25 UTC, NathanFlurry requested changes

2023-12-28 22:25 UTC, NathanFlurry commented on next.config.mjs
> +      {
Next redirects aren't supported for static builds. Need to use the `_redirects` file. This is where CF Pages is failing.

2024-01-04 18:06 UTC, AngelOnFira approved these changes

2024-01-10 23:27 UTC, NathanFlurry commented
this is awesome, good call

2024-01-10 23:27 UTC, NathanFlurry approved these changes

2024-01-10 23:29 UTC, merged