Spelling fixes
rivet-gg/site pull request #44
Opened 2023-12-30 04:02 UTC by AngelOnFira

2023-12-30 04:02 UTC, AngelOnFira commented
Current dependencies on/for this PR:
* `main`
  * **PR #44** <a href="https://app.graphite.dev/github/pr/rivet-gg/site/44?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/site/44?utm_source=stack-comment).

2023-12-30 04:04 UTC, AngelOnFira commented on src/pages/privacy.mdx
> +- The DATA's opt-out platform:{' '} [**http://optout.aboutads.info/?c=2&lang=EN**](http://optout.aboutads.info/?c=2&lang=EN)
Probably false positive

2023-12-30 05:54 UTC, NathanFlurry requested changes

2023-12-30 05:54 UTC, NathanFlurry commented on src/pages/privacy.mdx
> +- The DATA's opt-out platform:{' '} [**http://optout.aboutads.info/?c=2&lang=EN**](http://optout.aboutads.info/?c=2&lang=EN)
Yep, this needs to be reverted.

2024-01-03 01:22 UTC, AngelOnFira commented on src/pages/privacy.mdx
> +- The DATA's opt-out platform:{' '} [**http://optout.aboutads.info/?c=2&lang=EN**](http://optout.aboutads.info/?c=2&lang=EN)
```suggestion
- The DAA's opt-out platform:{' '} [**http://optout.aboutads.info/?c=2&lang=EN**](http://optout.aboutads.info/?c=2&lang=EN)
```

2024-01-05 00:36 UTC, NathanFlurry approved these changes

2024-01-05 03:07 UTC, merged