Add table of contents
rivet-gg/site pull request #62
Opened 2023-12-31 17:59 UTC by jog1t

Closes GDT-87

2023-12-31 21:00 UTC, NathanFlurry requested changes
Absolute legend.

A couple notes:

- The headings need to update as you scroll instead of the hash

- The media queries seem to not work correctly at a certain size

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/BIF3m0zL7mcrHUeMWh4D/980a5626-c1fd-4aad-a08b-3d84c0793fb7.png)

- I can't put my finger on the right solution, but the header on the right sidebar feels a bit off being misaligned with the text. We could either (a) align the header with the text, even though it looks weird or (b) remove the background on the buttons so we don't need padding around the buttons

- The header overlaps the main content oddly

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/BIF3m0zL7mcrHUeMWh4D/cc791d30-bd65-4e15-8faf-e8482c6ebe3f.png)

- Needs to have h1, h2, and h3 with indent like [here](https://syntax.tailwindui.com/docs/understanding-caching)

Fyi we have a license to all of the tailwind templates: https://tailwindui.com/templates/syntax

2023-12-31 22:13 UTC, NathanFlurry commented
@jog1t Awesome, you're probably right to roll this one out quickly. Let's fix #1 and #3 and we can merge this in asap.

2024-01-05 00:36 UTC, NathanFlurry requested changes
@jog1t this is honestly _so_ cool. clicked around a few other docs pages, this is night and day for our docs. 🙌 

I have a bunch more issues:

**Scroll ToC**

If easy, can we make this automatically keep the current tab in the view when scrolling? Note how the table of contents active selector goes out of view here:

<div class='graphite__hidden'>
          <div>🎥 Video uploaded on Graphite:</div>
            <a href="https://app.graphite.dev/media/video/BIF3m0zL7mcrHUeMWh4D/bb669964-7ffb-41d4-a28c-77bf665d6dd6.mov">
              <img src="https://app.graphite.dev/api/v1/graphite/video/thumbnail/BIF3m0zL7mcrHUeMWh4D/bb669964-7ffb-41d4-a28c-77bf665d6dd6.mov">
            </a>
          </div>
<video src="https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/BIF3m0zL7mcrHUeMWh4D/bb669964-7ffb-41d4-a28c-77bf665d6dd6.mov">Graphite Add Table of Contents.mov</video>

Going back to the GH actions, realizing that they actually do your original implementation (i.e. using the anchor), but imo this feels way more fluid.

**Tiny content area**

The content gets _super_ small on a small screen:

![Screenshot 2024-01-04 at 4.28.46 PM.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/BIF3m0zL7mcrHUeMWh4D/8d2c85c5-265f-4d2b-bf55-45ad323ad28b.png)

Compared to GH actions:

![Screenshot 2024-01-04 at 4.29.10 PM.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/BIF3m0zL7mcrHUeMWh4D/a5938ef7-2fe4-4fb3-b6d2-6aa53d475a13.png)

I'm wondering if we should collapse our left sidebar like they do or collapse the table of contents.

Related issues:

- https://linear.app/rivet-gg/issue/HUB-239/sidebar-nav-button-does-not-show-when-sidebar-is-hidden
- https://linear.app/rivet-gg/issue/HUB-240/header-logo-and-open-rivet-buttons-collapse-weirdly-on-smaller-screens

2024-01-09 06:26 UTC, AngelOnFira commented on src/components/TableOfContents.jsx
I found a bug where ToC will show sections that have been commented out. This is the code for the section:

```
{/* 
### Test locally

First, we can test that the game works locally.

Open the Rivet panel in the bottom left and click _Start Server_. Then click the
play button in the top right to start the client. You should be able to join the
lobby. */}
```

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XiP77c3NM4Q27xw9sqIb/ebbc5252-9d86-4ace-9ab1-05291b79f2a0.png)

2024-01-09 06:30 UTC, AngelOnFira commented on src/components/TableOfContents.jsx
Running into an issue on where the page will scroll to when clicking in the ToC

![Kapture 2024-01-09 at 01.28.43.gif](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XiP77c3NM4Q27xw9sqIb/e6fdc5fc-4df2-46a9-8f42-b9f4367f7944.gif)

2024-01-09 06:31 UTC, AngelOnFira requested changes
I ran into a few bugs to resolve 💯 sorry if either of them have already been brought up!

2024-01-10 23:28 UTC, NathanFlurry commented
@jog1t cf pages failing

2024-01-10 23:32 UTC, NathanFlurry requested changes
Getting this error:

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/BIF3m0zL7mcrHUeMWh4D/27c92c92-65e1-4a9b-849a-aa228f4a00d7.png)

2024-01-11 20:26 UTC, NathanFlurry approved these changes
dope

2024-01-13 19:39 UTC, AngelOnFira approved these changes

2024-01-13 19:39 UTC, AngelOnFira commented on src/components/Code.jsx
I'm still seeing some inconstancies on how it scrolls through on the right side, and when clicking on sections, it still doesn't seem to work all the time. I think it's good enough for now, and I can create separate tickets when I run into things.

![Kapture 2024-01-13 at 14.35.38.gif](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XiP77c3NM4Q27xw9sqIb/8dd0d671-f344-41fa-817c-27293833c638.gif)

2024-01-13 19:41 UTC, merged