Redesign mvp
rivet-gg/site pull request #71
Opened 2024-01-02 21:44 UTC by NicholasKissel

2024-01-08 08:51 UTC, NathanFlurry requested changes
Need to update game engine graphics, fix remaining links

2024-01-10 23:56 UTC, MasterPtato requested changes

2024-01-10 23:56 UTC, MasterPtato commented on src/pages/index.jsx
> +    href: 'https://github.com/rivet-gg/examples/tree/main/c/coredumpo',
typo, should be https://github.com/rivet-gg/examples/tree/main/c/coredumpohttps://github.com/rivet-gg/examples/tree/main/c/coredump

2024-01-10 23:56 UTC, MasterPtato commented on src/pages/index.jsx
> +    },
Are these supposed to all be the Godot image?

2024-01-11 00:00 UTC, MasterPtato requested changes

2024-01-11 00:00 UTC, MasterPtato commented on src/components/GlowBox.jsx
> +const creamColor = '#f0e5d6';
Nit: SCREAMING_CAMEL_CASE

2024-01-21 22:14 UTC, NathanFlurry approved these changes

2024-01-21 22:22 UTC, merged