Real Earth
rivet-gg/site pull request #82
Opened 2024-01-24 16:59 UTC by jog1t

Fixes HUB-332

2024-01-24 19:14 UTC, NathanFlurry requested changes
![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/BIF3m0zL7mcrHUeMWh4D/ea342f58-a9be-48c2-8f46-2ce9dcc59130.png)

weird bug.

just realized this is actually rendered in real time, this is super cool. thoughts on making it rotate in sync as you scroll, maybe with a lerp to make it smooth?

like make it spin by default, but add the rotation. ie `rotate = date.now() / 1000 + scroll.y/window.innerHeight`

2024-01-26 21:37 UTC, AngelOnFira requested changes

2024-01-26 21:37 UTC, AngelOnFira commented on src/pages/index.jsx
> +              scene='https://prod.spline.design/Xut0X1BT35gDbp4z/scene.splinecode'
Is this something we can host locally in case it goes down for whatever reason?

2024-01-26 21:37 UTC, AngelOnFira commented on src/pages/index.jsx
I could be mistaken, but it looks like clouds or the land is moving at a bit of a different pace. I think it's pedantic more than anything, and it still looks cool, but if it's easy to tweak, it could be worth checking out :)

2024-01-30 06:43 UTC, NathanFlurry requested changes
This is super cool. Do we have the appropriate license to use this?

Thoughts on adding a gradient to make the transition more fluid instead of using a white line on top? Like this (obv not overlaying text).

![Screenshot 2024-01-29 at 10.38.54 PM.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/BIF3m0zL7mcrHUeMWh4D/fe71f7cd-511e-45c9-a246-2ae6182086cf.png)

2024-01-31 21:07 UTC, AngelOnFira approved these changes

2024-02-01 21:19 UTC, NathanFlurry requested changes
lgtm. just need confirmation from @jog1t that the textures are something we have permission to use. i don't know where they came from.

2024-03-24 02:55 UTC, NathanFlurry commented
@jog1t i'm going to close this for now, we can re-open it later. there's some issues with jerkiness, performance, and alignment on my machine. it's very cool but i don't want to keep investing in it

2024-03-24 02:55 UTC, closed without merging