feat(WEB-100): new blog layout and narrower layout
rivet-gg/site pull request #86
Opened 2024-01-26 17:42 UTC by jog1t

Fixes WEB-100, fixes WEB-137

2024-01-26 21:56 UTC, AngelOnFira requested changes

2024-01-26 21:56 UTC, AngelOnFira commented on src/app/layout.tsx
On prod, it looks like

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XiP77c3NM4Q27xw9sqIb/c9409c20-6342-4315-bd3e-1d17eb3a7857.png)

On this branch, like this

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XiP77c3NM4Q27xw9sqIb/cbd36479-0514-4fa6-a864-ad5a3d778b4b.png)

2024-01-26 21:56 UTC, AngelOnFira commented on src/app/layout.tsx
I think for these pages, it would be best to not shrink the content, larger size is probably better

2024-01-26 21:56 UTC, AngelOnFira commented on src/app/layout.tsx
Old

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XiP77c3NM4Q27xw9sqIb/b5bbbc2c-e434-49f8-a0fa-301df08f66ac.png)

New

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XiP77c3NM4Q27xw9sqIb/6b90e557-98fe-4719-b06e-c440fb1a01fd.png)

2024-01-26 21:56 UTC, AngelOnFira commented on src/app/layout.tsx
Love the content width like this, curious about if the sidebars should be on the side or where they are right now. I think it can make it inconsistent on other pages (like in the other comment I posted).

2024-01-30 06:37 UTC, NathanFlurry requested changes
I _think_ I like it. I'm a little concerned about some of our in depth tutorials feeling a tad cramped. 

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/BIF3m0zL7mcrHUeMWh4D/812e1e47-5f3e-421f-9b1b-d131de948dc3.png)

What do you think about giving it a bit more breathing room?

2024-02-01 21:21 UTC, NathanFlurry commented
@jog1t yep, a wider container

2024-02-15 19:38 UTC, AngelOnFira commented
@kacper love how the narrow changes look, a few places I'm finding that might not do as well being changed over. I think everything under `/learn`, `/docs`, and `/blog` is good, but the home page and pricing should probably retain their current look.

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XiP77c3NM4Q27xw9sqIb/aaace0c4-0a38-4ae1-b216-212af144551a.png)

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/XiP77c3NM4Q27xw9sqIb/23cf6e12-61f2-4c47-a62f-0a13df22f51f.png)

2024-02-16 19:24 UTC, AngelOnFira requested changes
probably should have left this as a comment on a file: https://app.graphite.dev/github/pr/rivet-gg/site/86/Narrow-content#discussion-IC_kwDOJzZPfM50DpKv

2024-02-27 16:53 UTC, AngelOnFira commented
@jog1t bumping this for when it can go back on your plate :)

2024-02-28 00:38 UTC, AngelOnFira commented
@jog1t CI build is failing

2024-02-28 00:46 UTC, AngelOnFira requested changes
@jog1t  CI build is failing

2024-03-01 06:40 UTC, NathanFlurry requested changes
blog ui does not collapse for narrow width

other than that, lgtm, looking forward to shipping this

2024-03-01 06:41 UTC, NathanFlurry commented
also "packed to the brim with features" tabs are full width for some reason, when they're thinner on prod

the pricing page is oddly skinny too

2024-03-05 01:12 UTC, merged