Add lobby tags docs, add links to tiers and regions
rivet-gg/site pull request #87
Opened 2024-01-27 01:09 UTC by MasterPtato

2024-01-27 01:09 UTC, MasterPtato commented
Current dependencies on/for this PR:
* `main`
  * **PR #87** <a href="https://app.graphite.dev/github/pr/rivet-gg/site/87?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/site/87?utm_source=stack-comment).

2024-01-30 07:23 UTC, NathanFlurry requested changes

2024-01-30 07:23 UTC, NathanFlurry commented on src/pages/docs/dynamic-servers/concepts/available-tiers.mdx
>  - `basic-1d8`: 1/8 core, 250 MB RAM
Are these values accurate still? I know we updated the pricing page correctly.

2024-01-30 07:23 UTC, NathanFlurry commented on src/pages/docs/matchmaker/concepts/lobby-tags.mdx
> +Lobby tags are an optional property that can be passed to the [`lobbies.find`](/docs/matchmaker/api/lobbies/find), [`lobbies.join`](/docs/matchmaker/api/lobbies/join), and [`lobbies.create`](/docs/ma
Does lobbies.join use tags? How would that work?

2024-01-30 07:23 UTC, NathanFlurry commented on src/pages/docs/matchmaker/concepts/lobby-tags.mdx
> +When passed to [`lobbies.create`](/docs/matchmaker/api/lobbies/create), the newly created lobby will have the given tags.
I think this needs to clarify lobbies.find will set the tags too, right? I know you go in to this below in the example, but thrown off by this.

2024-01-30 07:23 UTC, NathanFlurry commented on src/pages/docs/matchmaker/concepts/lobby-tags.mdx
> +  and cases 1-3 would create a new lobby with the given tags only if all available servers are full.
Can we move this at the top? I think talking about "cases 4 and 5" adds more confusion and things to think about. Just something like "uses prevent auto create lobby to demonstrate how lobbies are selected"

2024-01-30 20:01 UTC, NathanFlurry approved these changes

2024-01-30 20:04 UTC, merged