Add docs on docker root user
rivet-gg/site pull request #95
Opened 2024-01-31 19:53 UTC by MasterPtato

2024-01-31 19:53 UTC, MasterPtato commented
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/rivet-gg/site/95?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

Current dependencies on/for this PR:
* `main`
  * **PR #90** <a href="https://app.graphite.dev/github/pr/rivet-gg/site/90?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 
    * **PR #95** <a href="https://app.graphite.dev/github/pr/rivet-gg/site/95?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a>  👈

This [stack of pull requests](https://stacking.dev/?utm_source=stack-comment) is managed by [Graphite](https://app.graphite.dev/github/pr/rivet-gg/site/95?utm_source=stack-comment).

2024-01-31 19:55 UTC, MasterPtato commented on src/pages/docs/dynamic-servers/concepts/docker-root-user.mdx
> +# Docker root user
@NathanFlurry relative changes here

2024-02-01 21:24 UTC, NathanFlurry requested changes

2024-02-01 21:24 UTC, NathanFlurry commented on src/pages/docs/dynamic-servers/concepts/docker-root-user.mdx
> +    ```
We don't need windows & macos.

2024-02-01 21:24 UTC, NathanFlurry commented on src/pages/docs/dynamic-servers/concepts/docker-root-user.mdx
> +Although Docker allows running containers as the root user, Rivet does not allow uploaded build images to use
I think a lot of people will come in to this not understanding how linux users work/why they're important. This paragraph is good, but might be good to add a "learn more" link to something that describes users in dockerfiles in an easy to understand way.

2024-02-01 21:24 UTC, NathanFlurry commented on src/pages/docs/dynamic-servers/concepts/docker-root-user.mdx
> +Although Docker allows running containers as the root user, Rivet does not allow uploaded build images to use
This whole document is _scary_ to someone who doesn't know how to use a cli. trying to make it less scary.

2024-02-06 18:40 UTC, AngelOnFira commented
@MasterPtato one thing I've found is separating PRs in the stack into one that just has formatting and one that has all the important changes. Makes it a bit easier to go through I think 🙌

2024-02-06 18:48 UTC, AngelOnFira approved these changes

2024-02-06 19:45 UTC, MasterPtato commented
> @MasterPtato one thing I've found is separating PRs in the stack into one that just has formatting and one that has all the important changes. Makes it a bit easier to go through I think 🙌 

Will do next time, thanks

2024-02-16 20:26 UTC, NathanFlurry requested changes
![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/BIF3m0zL7mcrHUeMWh4D/9362648a-05fc-40d9-90fb-23c103aa5c82.png)

Should split up the section in to "What is a root user?" and "How do I run my Docker container as a non-root user?"

Put "Rivet does not allow uploaded build images to run as the root user" in the intro paragraph

can't review specific code because of fmt. i'm planning on running a big fmt and re-enabling ci on it once all of these chnages are merged.

2024-02-16 23:19 UTC, MasterPtato commented
@NathanFlurry hows this? i think its more cohesive

![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/WoaiNOUjGiXic7rsR2cI/2291daad-700a-4c87-9040-e82cc7ccdd14.png)

2024-02-16 23:22 UTC, NathanFlurry commented
> @NathanFlurry hows this? i think its more cohesive
> 
> ![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/WoaiNOUjGiXic7rsR2cI/2291daad-700a-4c87-9040-e82cc7ccdd14.png)
> 
> 

lgtm

2024-02-16 23:22 UTC, NathanFlurry approved these changes
![image.png](https://graphite-user-uploaded-assets-prod.s3.amazonaws.com/BIF3m0zL7mcrHUeMWh4D/9362648a-05fc-40d9-90fb-23c103aa5c82.png)

Should split up the section in to "What is a root user?" and "How do I run my Docker container as a non-root user?"

Put "Rivet does not allow uploaded build images to run as the root user" in the intro paragraph

can't review specific code because of fmt. i'm planning on running a big fmt and re-enabling ci on it once all of these chnages are merged.

2024-02-16 23:29 UTC, merged